
[project]
name = "sentiment-analysis"
version = "0.1.0"
dependencies = []

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project.scripts]
analysis = "analyse.__main__:main"
